package com.akina.bean;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer userId;

    /**
     * 用户
     */
    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.pic_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer picId;


    /**
     * 图片
     */
    private Picture pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String commentInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.pic_id
     *
     * @return the value of comment.pic_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.pic_id
     *
     * @param picId the value for comment.pic_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_info
     *
     * @return the value of comment.comment_info
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getCommentInfo() {
        return commentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_info
     *
     * @param commentInfo the value for comment.comment_info
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setCommentInfo(String commentInfo) {
        this.commentInfo = commentInfo == null ? null : commentInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    public Picture getPic() {
        return pic;
    }

    public void setPic(Picture pic) {
        this.pic = pic;
    }

    public Comment(Integer commentId, Integer userId, Integer picId, String commentInfo, Date createTime) {
        this.commentId = commentId;
        this.userId = userId;
        this.picId = picId;
        this.commentInfo = commentInfo;
        this.createTime = createTime;
    }

    public Comment() {
    }

    @Override
    public String toString() {
        return "Comment{" +
                "commentId=" + commentId +
                ", userId=" + userId +
                ", user=" + user +
                ", picId=" + picId +
                ", pic=" + pic +
                ", commentInfo='" + commentInfo + '\'' +
                ", createTime=" + createTime +
                '}';
    }
}