package com.akina.bean;

import java.util.Date;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_id
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private Integer picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.user_id
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private Integer userId;


    private User user;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_name
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_ispixiv
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private Integer picIspixiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_http_path
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private String picHttpPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_floor_price
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private String picFloorPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_present_price
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private String picPresentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_trim_times
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private Integer picTrimTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_ state
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private Integer picState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_key
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private String picKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.create_time
     *
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_id
     *
     * @return the value of picture.pic_id
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_id
     *
     * @param picId the value for picture.pic_id
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.user_id
     *
     * @return the value of picture.user_id
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.user_id
     *
     * @param userId the value for picture.user_id
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_name
     *
     * @return the value of picture.pic_name
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_name
     *
     * @param picName the value for picture.pic_name
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_ispixiv
     *
     * @return the value of picture.pic_ispixiv
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public Integer getPicIspixiv() {
        return picIspixiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_ispixiv
     *
     * @param picIspixiv the value for picture.pic_ispixiv
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicIspixiv(Integer picIspixiv) {
        this.picIspixiv = picIspixiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_http_path
     *
     * @return the value of picture.pic_http_path
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public String getPicHttpPath() {
        return picHttpPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_http_path
     *
     * @param picHttpPath the value for picture.pic_http_path
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicHttpPath(String picHttpPath) {
        this.picHttpPath = picHttpPath == null ? null : picHttpPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_floor_price
     *
     * @return the value of picture.pic_floor_price
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public String getPicFloorPrice() {
        return picFloorPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_floor_price
     *
     * @param picFloorPrice the value for picture.pic_floor_price
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicFloorPrice(String picFloorPrice) {
        this.picFloorPrice = picFloorPrice == null ? null : picFloorPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_present_price
     *
     * @return the value of picture.pic_present_price
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public String getPicPresentPrice() {
        return picPresentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_present_price
     *
     * @param picPresentPrice the value for picture.pic_present_price
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicPresentPrice(String picPresentPrice) {
        this.picPresentPrice = picPresentPrice == null ? null : picPresentPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_trim_times
     *
     * @return the value of picture.pic_trim_times
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public Integer getPicTrimTimes() {
        return picTrimTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_trim_times
     *
     * @param picTrimTimes the value for picture.pic_trim_times
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicTrimTimes(Integer picTrimTimes) {
        this.picTrimTimes = picTrimTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_ state
     *
     * @return the value of picture.pic_ state
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public Integer getPicState() {
        return picState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_ state
     *
     * @param picState the value for picture.pic_ state
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicState(Integer picState) {
        this.picState = picState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_key
     *
     * @return the value of picture.pic_key
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public String getPicKey() {
        return picKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_key
     *
     * @param picKey the value for picture.pic_key
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setPicKey(String picKey) {
        this.picKey = picKey == null ? null : picKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.create_time
     *
     * @return the value of picture.create_time
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.create_time
     *
     * @param createTime the value for picture.create_time
     * @mbggenerated Sun May 21 00:51:46 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Picture(Integer picId, Integer userId, String picName, Integer picIspixiv, String picHttpPath, String picFloorPrice, String picPresentPrice, Integer picTrimTimes, Integer picState, String picKey, Date createTime) {
        this.picId = picId;
        this.userId = userId;
        this.picName = picName;
        this.picIspixiv = picIspixiv;
        this.picHttpPath = picHttpPath;
        this.picFloorPrice = picFloorPrice;
        this.picPresentPrice = picPresentPrice;
        this.picTrimTimes = picTrimTimes;
        this.picState = picState;
        this.picKey = picKey;
        this.createTime = createTime;
    }

    public Picture() {
    }

    @Override
    public String toString() {
        return "Picture{" +
                "picId=" + picId +
                ", userId=" + userId +
                ", user=" + user +
                ", picName='" + picName + '\'' +
                ", picIspixiv=" + picIspixiv +
                ", picHttpPath='" + picHttpPath + '\'' +
                ", picFloorPrice='" + picFloorPrice + '\'' +
                ", picPresentPrice='" + picPresentPrice + '\'' +
                ", picTrimTimes=" + picTrimTimes +
                ", picState=" + picState +
                ", picKey='" + picKey + '\'' +
                ", createTime=" + createTime +
                '}';
    }
}