package com.akina.bean;

import java.util.Date;

public class Talk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.talk_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer talkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.send_user_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer sendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.receive_user_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer receiveUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.unread_number
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer unreadNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.create_time
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.talk_id
     *
     * @return the value of talk.talk_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getTalkId() {
        return talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.talk_id
     *
     * @param talkId the value for talk.talk_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setTalkId(Integer talkId) {
        this.talkId = talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.send_user_id
     *
     * @return the value of talk.send_user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.send_user_id
     *
     * @param sendUserId the value for talk.send_user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.receive_user_id
     *
     * @return the value of talk.receive_user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.receive_user_id
     *
     * @param receiveUserId the value for talk.receive_user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setReceiveUserId(Integer receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.unread_number
     *
     * @return the value of talk.unread_number
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getUnreadNumber() {
        return unreadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.unread_number
     *
     * @param unreadNumber the value for talk.unread_number
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUnreadNumber(Integer unreadNumber) {
        this.unreadNumber = unreadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.create_time
     *
     * @return the value of talk.create_time
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.create_time
     *
     * @param createTime the value for talk.create_time
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    public Talk(Integer talkId, Integer sendUserId, Integer receiveUserId, Integer unreadNumber, Date createTime) {
        this.talkId = talkId;
        this.sendUserId = sendUserId;
        this.receiveUserId = receiveUserId;
        this.unreadNumber = unreadNumber;
        this.createTime = createTime;
    }

    public Talk() {
    }

    @Override
    public String toString() {
        return "Talk{" +
                "talkId=" + talkId +
                ", sendUserId=" + sendUserId +
                ", receiveUserId=" + receiveUserId +
                ", unreadNumber=" + unreadNumber +
                ", createTime=" + createTime +
                '}';
    }
}