package com.akina.bean;

import java.util.Date;

public class TalkInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_info.talk_info_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer talkInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_info.talk_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String talkInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_info.talk_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer talkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_info.user_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_info.read_flag
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer readFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_info.create_time
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_info.talk_info_id
     *
     * @return the value of talk_info.talk_info_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getTalkInfoId() {
        return talkInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_info.talk_info_id
     *
     * @param talkInfoId the value for talk_info.talk_info_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setTalkInfoId(Integer talkInfoId) {
        this.talkInfoId = talkInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_info.talk_info
     *
     * @return the value of talk_info.talk_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getTalkInfo() {
        return talkInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_info.talk_info
     *
     * @param talkInfo the value for talk_info.talk_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setTalkInfo(String talkInfo) {
        this.talkInfo = talkInfo == null ? null : talkInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_info.talk_id
     *
     * @return the value of talk_info.talk_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getTalkId() {
        return talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_info.talk_id
     *
     * @param talkId the value for talk_info.talk_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setTalkId(Integer talkId) {
        this.talkId = talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_info.user_id
     *
     * @return the value of talk_info.user_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_info.user_id
     *
     * @param userId the value for talk_info.user_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_info.read_flag
     *
     * @return the value of talk_info.read_flag
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_info.read_flag
     *
     * @param readFlag the value for talk_info.read_flag
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setReadFlag(Integer readFlag) {
        this.readFlag = readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_info.create_time
     *
     * @return the value of talk_info.create_time
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_info.create_time
     *
     * @param createTime the value for talk_info.create_time
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}