package com.akina.bean;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_mail
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pwd
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pixiv
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String userPixiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_abstract
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String userAbstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_head_path
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String userHeadPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pay_path
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private String userPayPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_integral
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer userIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_mail
     *
     * @return the value of user.user_mail
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_mail
     *
     * @param userMail the value for user.user_mail
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pwd
     *
     * @return the value of user.user_pwd
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pwd
     *
     * @param userPwd the value for user.user_pwd
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pixiv
     *
     * @return the value of user.user_pixiv
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getUserPixiv() {
        return userPixiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pixiv
     *
     * @param userPixiv the value for user.user_pixiv
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserPixiv(String userPixiv) {
        this.userPixiv = userPixiv == null ? null : userPixiv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_abstract
     *
     * @return the value of user.user_abstract
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getUserAbstract() {
        return userAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_abstract
     *
     * @param userAbstract the value for user.user_abstract
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserAbstract(String userAbstract) {
        this.userAbstract = userAbstract == null ? null : userAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_head_path
     *
     * @return the value of user.user_head_path
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getUserHeadPath() {
        return userHeadPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_head_path
     *
     * @param userHeadPath the value for user.user_head_path
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserHeadPath(String userHeadPath) {
        this.userHeadPath = userHeadPath == null ? null : userHeadPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pay_path
     *
     * @return the value of user.user_pay_path
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public String getUserPayPath() {
        return userPayPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pay_path
     *
     * @param userPayPath the value for user.user_pay_path
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserPayPath(String userPayPath) {
        this.userPayPath = userPayPath == null ? null : userPayPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_integral
     *
     * @return the value of user.user_integral
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getUserIntegral() {
        return userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_integral
     *
     * @param userIntegral the value for user.user_integral
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserIntegral(Integer userIntegral) {
        this.userIntegral = userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    public User(Integer userId, String userName, String userMail, String userPwd, String userPixiv, String userAbstract, String userHeadPath, String userPayPath, Integer userIntegral, Date createTime) {
        this.userId = userId;
        this.userName = userName;
        this.userMail = userMail;
        this.userPwd = userPwd;
        this.userPixiv = userPixiv;
        this.userAbstract = userAbstract;
        this.userHeadPath = userHeadPath;
        this.userPayPath = userPayPath;
        this.userIntegral = userIntegral;
        this.createTime = createTime;
    }

    public User() {
    }

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userMail='" + userMail + '\'' +
                ", userPwd='" + userPwd + '\'' +
                ", userPixiv='" + userPixiv + '\'' +
                ", userAbstract='" + userAbstract + '\'' +
                ", userHeadPath='" + userHeadPath + '\'' +
                ", userPayPath='" + userPayPath + '\'' +
                ", userIntegral=" + userIntegral +
                ", createTime=" + createTime +
                '}';
    }
}