package com.akina.bean;

import java.util.Date;

public class UserTrimPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trim_price.id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trim_price.user_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer userId;
    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trim_price.pic_id
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer picId;
    private Picture pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trim_price.trim_tape
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Integer trimTape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trim_price.price
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_trim_price.create_time
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trim_price.id
     *
     * @return the value of user_trim_price.id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trim_price.id
     *
     * @param id the value for user_trim_price.id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trim_price.user_id
     *
     * @return the value of user_trim_price.user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trim_price.user_id
     *
     * @param userId the value for user_trim_price.user_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trim_price.pic_id
     *
     * @return the value of user_trim_price.pic_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trim_price.pic_id
     *
     * @param picId the value for user_trim_price.pic_id
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trim_price.trim_tape
     *
     * @return the value of user_trim_price.trim_tape
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Integer getTrimTape() {
        return trimTape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trim_price.trim_tape
     *
     * @param trimTape the value for user_trim_price.trim_tape
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setTrimTape(Integer trimTape) {
        this.trimTape = trimTape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trim_price.price
     *
     * @return the value of user_trim_price.price
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trim_price.price
     *
     * @param price the value for user_trim_price.price
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_trim_price.create_time
     *
     * @return the value of user_trim_price.create_time
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_trim_price.create_time
     *
     * @param createTime the value for user_trim_price.create_time
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Picture getPic() {
        return pic;
    }

    public void setPic(Picture pic) {
        this.pic = pic;
    }

    public UserTrimPrice(Integer id, Integer userId, Integer picId, Integer trimTape, Double price, Date createTime) {
        this.id = id;
        this.userId = userId;
        this.picId = picId;
        this.trimTape = trimTape;
        this.price = price;
        this.createTime = createTime;
    }

    public UserTrimPrice() {
    }

    @Override
    public String toString() {
        return "UserTrimPrice{" +
                "id=" + id +
                ", userId=" + userId +
                ", user=" + user +
                ", picId=" + picId +
                ", pic=" + pic +
                ", trimTape=" + trimTape +
                ", price=" + price +
                ", createTime=" + createTime +
                '}';
    }
}