package com.akina.mapper;

import com.akina.bean.Comment;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;


@Component
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    Comment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int updateByPrimaryKey(Comment record);

    /**=======================================================**/

    /***
     *
     * @return
     */
    Integer findCommentCount(@Param("pic_id") Integer pic_id);


    /****
     * 分页查询数据
     *
     * @param start
     *            起始条数
     * @param size
     *            每页显示条数
     *
     * @return List<Comment>
     */
    List<Comment> findCommentDate(@Param("start") Integer start, @Param("size") Integer size, @Param("pic_id") Integer pic_id);
}