package com.akina.mapper;

import com.akina.bean.TalkInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface TalkInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int deleteByPrimaryKey(Integer talkInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int insert(TalkInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    TalkInfo selectByPrimaryKey(Integer talkInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    List<TalkInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk_info
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int updateByPrimaryKey(TalkInfo record);


    /**================================================**/


    /***
     * 按照会话id查询所有对话内容
     * @param talk_id  会话id
     * @return
     */
    List<TalkInfo> findAll(@Param("talk_id") Integer talk_id);


    /***
     * 按照所属会话删除
     * @param talk_id
     * @return
     */
    Integer deleteByTalkId(@Param("talk_id") Integer talk_id);
}