package com.akina.mapper;

import com.akina.bean.Talk;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface TalkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int deleteByPrimaryKey(Integer talkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int insert(Talk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    Talk selectByPrimaryKey(Integer talkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    List<Talk> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talk
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int updateByPrimaryKey(Talk record);

    /**========================================================**/

    /***
     * 按照userid返回会话集合
     * @param user_id  用户id
     * @return
     */
    List<Talk> findAllByUser(@Param("user_id") Integer user_id);


    /**
     * 查询所有未读消息之和
     *
     * @return
     */
    Integer findUnreadNumber();


    /***
     * 根据会话id  对未读消息+1  发送私信后执行
     * @param talk_id
     * @return
     */
    Integer updateUnread(Integer talk_id);

}