package com.akina.mapper;

import com.akina.bean.UserTrimPrice;
import org.springframework.stereotype.Component;

import java.util.List;


@Component
public interface UserTrimPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_trim_price
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_trim_price
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int insert(UserTrimPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_trim_price
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    UserTrimPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_trim_price
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    List<UserTrimPrice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_trim_price
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int updateByPrimaryKey(UserTrimPrice record);


    /**============================================**/

}