package com.akina.mapper;

import com.akina.bean.User;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;


@Component
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 20 23:37:32 CST 2017
     */
    int updateByPrimaryKey(User record);


    /**========================================================================**/

    /**
     * 按照用户邮箱和已经进过MD5加密后的密码查询
     *
     * @param mail 邮箱
     * @param s    已经被MD5加密后的密码
     * @return 返回查询结果
     */
    User selectUserBypram(@Param("mail") String mail, @Param("pwd") String s);


    /***
     * 按照邮箱查询用户
     * @param mail 邮箱
     * @return 返回查询结果 ，用于用户注册的时候判断重复
     */
    User selectUserByMail(@Param("mail") String mail);


}